GET http://localhost:3000/llm/
content-type: application/json

###

POST http://localhost:3000/user/login
content-type: application/json

{
    "email": "admin@email.com",
    "password": "Password123!"
}

###

GET http://localhost:3000/llm/single?id=66991d803140a8d1e4c2b297
content-type: application/json